package com.myspace.noticedatamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ActionOutput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String actionCode;

	public ActionOutput() {
	}

	public java.lang.String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(java.lang.String actionCode) {
		this.actionCode = actionCode;
	}

	public ActionOutput(java.lang.String actionCode) {
		this.actionCode = actionCode;
	}

}