package com.myspace.noticedatamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ActionOutput implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ActionOutput() {
    }




}