package com.myspace.noticedatamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LetterGreetingOutput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String lgCode;

	public LetterGreetingOutput() {
	}

	public java.lang.String getLgCode() {
		return this.lgCode;
	}

	public void setLgCode(java.lang.String lgCode) {
		this.lgCode = lgCode;
	}

	public LetterGreetingOutput(java.lang.String lgCode) {
		this.lgCode = lgCode;
	}

}